configData:
  configpw:
    encrypt: true
    value: !!binary |
      WVdSdGFXND0=
sqlConnection:
  db:
    encrypt: false
    read: false
    value: test
  host:
    encrypt: false
    read: true
    value: 127.0.0.1
  password:
    encrypt: true
    read: true
    value: !!binary |
      Vlc5d2NEazJNek14SVE9PQ==
  user:
    encrypt: true
    read: true
    value: !!binary |
      Y205dmRBPT0=
