configData:
  configpw:
    encrypt: true
    value: !!binary |
      WVdSdGFXND0=
sqlConnection:
  host:
    encrypt: false
    value: null
  port:
    encrypt: false
    value: null
  sqlpassword:
    encrypt: true
    value: null
  user:
    encrypt: true
    value: null
